# Configure when notifications should be sent for each
# type of event. Each even can have multiple notification
# times.
# Each key in the events map should have a list of X minutes
# where X is how many minutes before the event a notification
# should be sent.
events:
  practice:
    - 60
  sprint_quali:
    - 60
    - 1440
  quali:
    - 60
    - 1440
  sprint:
    - 60
    - 1440
  race:
    - 60
    - 1440
